name: "mantra-benchmarks"
services:
  mantra_service:
    image: mantra_img:0
    container_name: mantra_container
    build: .
    ipc: host
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - "./code:/code"
      - "./data:/data"
  