wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716056889.501385
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.11
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
