wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716112566.819861
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      - 105
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      - 105
      3:
      - 23
      - 24
      4: 3.10.11
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
