conf_model:
  hidden_channels: 64
  num_hidden_layers: 3
  num_node_features: 8
  out_channels: 1
learning_rate: 0.01
seed: 1234
task_type: orientability
trainer_config:
  accelerator: auto
  log_every_n_steps: 1
  max_epochs: 50
transforms: random_node_features
type_model: gcn
use_stratified: true
