task: betti_numbers
model:
  model_name: MLP
  num_hidden_neurons: 64
  num_hidden_layers: 3
  num_node_features: 9
  out_channels: 3
trainer:
  accelerator: auto
  max_epochs: 50
  log_every_n_steps: 1
litmodel:
  learning_rate: 0.01
data:
  transforms: degree_transform_onehot
  use_stratified: false
  seed: 1234
